march:
  controller:
    state:
      type: joint_state_controller/JointStateController
      publish_rate: 50
    temperature_sensor:
      type: march_temperature_sensor_controller/MarchTemperatureSensorController
      publish_rate: 50
    trajectory:
      testjoint:
        type: effort_controllers/JointTrajectoryController
        joints:
          - test_joint
        gains: # Required because we're controlling an effort interface
          test_joint: {p: 100000, i: 10000, d: 1, i_clamp: 10, publish_state: true, antiwindup: true}
    effort_controller:
      type: "effort_controllers/JointEffortController"
      joint: test_joint
