joint_limits:
  test_joint:
    has_position_limits: true
    min_position: -0.0872664626
    max_position: 2.00713
    has_velocity_limits: true
    max_velocity: 0.4

    has_soft_limits: true
    soft_lower_limit: -0.04
    soft_upper_limit: 1.75
#    soft_lower_limit: 0.5
#    soft_upper_limit: 1
    k_position: 10.0
    k_velocity: 25000

    has_effort_limits: true
    max_effort: 10000.0
