joint_limits:
  test_joint:
    has_position_limits: true
    min_position: -0.0872664626
    max_position: 2.00713
    has_velocity_limits: true
    max_velocity: 2

    has_soft_limits: true
    soft_lower_limit: -0.22
    soft_upper_limit: 10.572
#    soft_lower_limit: 0.5
#    soft_upper_limit: 1
    k_position: 10.0
    k_velocity: 25000

    has_effort_limits: true
    max_effort: 20000.0