march:
  controller:
    state:
      type: joint_state_controller/JointStateController
      publish_rate: 50
    trajectory:
      full_exoskeleton:
        type: effort_controllers/JointTrajectoryController
        joints:
          - right_hip
          - left_hip
          - right_knee
          - left_knee
          - right_ankle
          - left_ankle
        gains: # Required because we're controlling an effort interface
          right_hip: {p: 1000, i: 100, d: 1, i_clamp: 10, publish_state: true, antiwindup: true}
          left_hip: {p: 1000, i: 100, d: 1, i_clamp: 10, publish_state: true, antiwindup: true}
          right_knee: {p: 1000, i: 100, d: 1, i_clamp: 10, publish_state: true, antiwindup: true}
          left_knee: {p: 1000, i: 100, d: 1, i_clamp: 10, publish_state: true, antiwindup: true}
          right_ankle: {p: 100, i: 10, d: 1, i_clamp: 10, publish_state: true, antiwindup: true}
          left_ankle: {p: 100, i: 10, d: 1, i_clamp: 10, publish_state: true, antiwindup: true}
