march:
  joint_inertia_controller:
    type: joint_inertia_controller/InertiaController
    joints:
      - left_ankle
      - left_hip_aa
      - left_hip_fe
      - left_knee
      - right_ankle
      - right_hip_aa
      - right_hip_fe
      - right_knee
