march:
  controller:
    pdb_state:
      type: march_pdb_state_controller/MarchPdbStateController
      publish_rate: 50
    joint_state:
      type: joint_state_controller/JointStateController
      publish_rate: 50
    temperature_sensor:
      type: march_temperature_sensor_controller/MarchTemperatureSensorController
      publish_rate: 1
    trajectory_effort:
      type: effort_controllers/JointTrajectoryController
      state_publish_rate: 250
      allow_partial_joints_goal: true
      joints:
        - right_hip_fe
        - left_hip_fe
        - right_knee
        - left_knee
#        - right_ankle
#        - left_ankle
      gains: # Required because we're controlling an effort interface
        right_hip_fe: {p: 10, i: 0, d: 0, i_clamp: 10, publish_state: true, antiwindup: true}
        left_hip_fe: {p: 10, i: 0, d: 0, i_clamp: 10, publish_state: true, antiwindup: true}
        right_knee: {p: 10, i: 0, d: 0, i_clamp: 10, publish_state: true, antiwindup: true}
        left_knee: {p: 10, i: 0, d: 0, i_clamp: 10, publish_state: true, antiwindup: true}
      trajectory_position:
        type: position_controllers/JointTrajectoryController
        joints:
          - right_hip_fe
          - left_hip_fe
          - right_knee
          - left_knee
#          - right_ankle
#          - left_ankle
