march:
  controller:
    state:
      type: joint_state_controller/JointStateController
      publish_rate: 50
    temperature_sensor:
      type: march_temperature_sensor_controller/MarchTemperatureSensorController
      publish_rate: 50
    trajectory:
      full_exoskeleton:
        type: effort_controllers/JointTrajectoryController
        joints:
          - right_hip_fe
        gains: # Required because we're controlling an effort interface
          right_hip_fe: {p: 20000, i: 1000, d: 1, i_clamp: 10, publish_state: true, antiwindup: true}
