march:
  controller:
    state:
      type: joint_state_controller/JointStateController
      publish_rate: 50
    temperature_sensor:
      type: march_temperature_sensor_controller/MarchTemperatureSensorController
      publish_rate: 50
    trajectory:
      full_exoskeleton:
        type: position_controllers/JointTrajectoryController
        joints:
          - right_hip_fe
          - left_hip_fe
          - right_knee
          - left_knee
