march:
  controller:
    pdb_state:
      type: march_pdb_state_controller/MarchPdbStateController
      publish_rate: 50
    joint_state:
      type: joint_state_controller/JointStateController
      publish_rate: 50
    temperature_sensor:
      type: march_temperature_sensor_controller/MarchTemperatureSensorController
      publish_rate: 1
    trajectory_effort:
      type: effort_controllers/JointTrajectoryController
      joints:
        - right_hip_fe
        - left_hip_fe
        - right_knee
        - left_knee
        - right_ankle
        - left_ankle
      gains: # Required because we're controlling an effort interface
        test_joint: {p: 80000, i: 1000, d: 1, i_clamp: 10, publish_state: true, antiwindup: true}
      trajectory_position:
        type: position_controllers/JointTrajectoryController
        joints:
          - right_hip_fe
          - left_hip_fe
          - right_knee
          - left_knee
          - right_ankle
          - left_ankle
