march:
  controller:
    pdb_state:
      type: march_pdb_state_controller/MarchPdbStateController
      publish_rate: 50
    joint_state:
      type: joint_state_controller/JointStateController
      publish_rate: 50
    temperature_sensor:
      type: march_temperature_sensor_controller/MarchTemperatureSensorController
      publish_rate: 50
    trajectory:
      type: position_controllers/JointTrajectoryController
      joints:
        - right_hip_fe
        - right_knee

#      gains:
#        right_hip_fe: {p: 2000, i: 1000, d: 1, i_clamp: 10, publish_state: true, antiwindup: true}
#        right_knee: {p: 2000, i: 1000, d: 1, i_clamp: 10, publish_state: true, antiwindup: true}
