march:
  controller:
    joint_state:
      type: joint_state_controller/JointStateController
      publish_rate: 50
    temperature_sensor:
      type: march_temperature_sensor_controller/MarchTemperatureSensorController
      publish_rate: 50
    pdb_state:
      type: march_pdb_state_controller/MarchPdbStateController
      publish_rate: 50
    trajectory:
      type: position_controllers/JointTrajectoryController
      joints:
        - rotational_joint
      constraints:
        rotational_joint:
          margin_soft_limit_error: 0.5
          trajectory: 0.305
          goal: 0.305
